language: node_js

node_js:
  - node

cache: npm

services: mongodb

jobs:
  include:
    - stage: test
      script: npm test
    - stage: deploy stack
      deploy:
        provider: cloudformation
        access_key_id: $AWS_ACCESS_KEY_ID
        secret_access_key:
          secure: $AWS_SECRET_ACCESS_KEY
        template: ./deployments/stack.yaml
        region: $AWS_DEFAULT_REGION
        stack_name: mirai-app
        edge: true
    - stage: deploy app
      script:
        - cd $TRAVIS_BUILD_DIR
        - aws s3api head-object --bucket mirai-app --key config.json || not_exists=true
        - if [ $not_exists ]; then echo "$CONFIG" > ./config/config.json; aws s3 cp ./config/config.json s3://mirai-app/config.json/; else aws s3 cp s3://mirai-app/config.json/ ./config/config.json; fi
        - jq -c '.application.travis_build = $buildNum' --arg buildNum $TRAVIS_BUILD_NUMBER ./config/config.json > ./config/config.json
        - jq -c '.application.environment = $env' --arg env 'prod' ./config/config.json > ./config/config.json
        - npm install
        - zip -r ./deployments/deploy.zip *
      deploy:
        - provider: elasticbeanstalk
          access_key_id: $AWS_ACCESS_KEY_ID
          secret_access_key:
            secure: $AWS_SECRET_ACCESS_KEY
          region: $AWS_DEFAULT_REGION
          app: mirai-app
          env: mirai-app
          bucket_name: mirai-app
          zip_file: ./deployments/deploy.zip
          skip_cleanup: true
          edge: true
          on:
            branch: $TRAVIS_BRANCH
          
stages:
  - test
  - name: deploy stack
    if: branch = master
  - name: deploy app
    if: branch = master

after_failure:
  - sleep 5