language: node_js

node_js:
  - node

cache: npm

services: mongodb

jobs:
  include:
    - stage: test
      script: 
        - cd $TRAVIS_BUILD_DIR/scripts
        - chmod +x config.sh
        - ./config.sh mirai-app-dev
        - node ../src/migrations/migrator.js
        - npm test
    - stage: deploy stack
      deploy:
        provider: cloudformation
        access_key_id: $AWS_ACCESS_KEY_ID
        secret_access_key:
          secure: $AWS_SECRET_ACCESS_KEY
        template: ./deployments/stack.yaml
        region: $AWS_DEFAULT_REGION
        stack_name: mirai-app
        edge: true
    - stage: migrate (prod)
      script:
        - cd $TRAVIS_BUILD_DIR/scripts
        - chmod +x config.sh
        - ./config.sh mirai-app
        - node ../src/migrations/migrator.js
    - stage: deploy app
      script:
        - cd $TRAVIS_BUILD_DIR/scripts
        - chmod +x config.sh
        - ./config.sh mirai-app
        - jq -c '.application.travis_build = ($buildNum | tonumber)' --arg buildNum $TRAVIS_BUILD_NUMBER ./config/config.json > ./config/config2.json
        - jq -c '.application.environment = $env' --arg env 'prod' ./config/config.json > ./config/config2.json
        - jq -c '.log.debug = ($flag | test("true"))' --arg flag true ./config/config.json > ./config/config2.json
        - mv ./config/config2.json ./config/config.json
        - npm install
        - zip -r ./deployments/deploy.zip *
      deploy:
        - provider: elasticbeanstalk
          access_key_id: $AWS_ACCESS_KEY_ID
          secret_access_key:
            secure: $AWS_SECRET_ACCESS_KEY
          region: $AWS_DEFAULT_REGION
          app: mirai-app
          env: mirai-app
          bucket_name: mirai-app
          zip_file: ./deployments/deploy.zip
          skip_cleanup: true
          edge: true
          on:
            branch: $TRAVIS_BRANCH
          
stages:
  - test
  - name: deploy stack
    if: branch = master
  - name: migrate (prod)
    if: branch = master
  - name: deploy app
    if: branch = master

after_failure:
  - sleep 5