AWSTemplateFormatVersion: '2010-09-09'

Resources:
  MiraiApplication:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      ApplicationName: mirai-app-prod
      Description: AWS Elastic Beanstalk Mirai
  MiraiConfigurationTemplate:
    Type: AWS::ElasticBeanstalk::ConfigurationTemplate
    Properties:
      ApplicationName:
        Ref: MiraiApplication
      Description: AWS ElasticBeanstalk Mirai Configuration Template
      OptionSettings:
      - Namespace: aws:autoscaling:asg
        OptionName: MinSize
        Value: '2'
      - Namespace: aws:autoscaling:asg
        OptionName: MaxSize
        Value: '6'
      - Namespace: aws:elasticbeanstalk:environment
        OptionName: EnvironmentType
        Value: LoadBalanced
      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: IamInstanceProfile
        Value: aws-elasticbeanstalk-ec2-role
      SolutionStackName: 64bit Amazon Linux 2018.03 v4.13.0 running Node.js
  MiraiApplicationVersion:
    Type: AWS::ElasticBeanstalk::ApplicationVersion
    Properties:
      Description: 1.0.0
      ApplicationName: 
        Ref: MiraiApplication
      SourceBundle:
        S3Bucket: elasticbeanstalk-samples-us-east-2
        S3Key: nodejs-sample-v2.zip
  MiraiEnvironment:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      ApplicationName:
        Ref: MiraiApplication
      EnvironmentName: mirai-app-prod
      Description: AWS ElasticBeanstalk Mirai Environment
      VersionLabel:
        Ref: MiraiApplicationVersion
      TemplateName:
        Ref: MiraiConfigurationTemplate
      OptionSettings:
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: InstanceType
          Value: t2.micro
Outputs:
  URL:
    Description: Mirai's URL
    Value:
      Fn::Join:
        - ""
        -
          - "http://"
          - Fn::GetAtt: MiraiEnvironment.EndpointURL